version: "3.8"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/servarr/radarr/config:/config
      - /mnt/shared/media/movies:/movies
    ports:
      - "7878:7878"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/servarr/sonarr/config:/config
      - /mnt/shared/media/tv:/tv
    ports:
      - "8989:8989"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/servarr/prowlarr/config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/servarr/lidarr/config:/config
      - /mnt/shared/media/music:/music
    ports:
      - "8686:8686"
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/servarr/readarr/config:/config
      - /mnt/shared/media/books:/books
    ports:
      - "8787:8787"
    restart: unless-stopped
